CREATE TABLE IF NOT EXISTS paper_trading_config (
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL PRIMARY KEY,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  initial_balance DECIMAL(18,8) NOT NULL DEFAULT 100,
  allocation_pct DECIMAL(6,3) NOT NULL DEFAULT 25,
  allow_short TINYINT(1) NOT NULL DEFAULT 1,
  avoid_volatile TINYINT(1) NOT NULL DEFAULT 1,
  fee_pct DECIMAL(8,5) NOT NULL DEFAULT 0.10,
  slippage_pct DECIMAL(8,5) NOT NULL DEFAULT 0.02,
  min_edge_pct DECIMAL(8,5) NOT NULL DEFAULT 0.03,
  min_confidence DECIMAL(6,5) NOT NULL DEFAULT 0.20,
  cooldown_minutes INT UNSIGNED NOT NULL DEFAULT 15,
  reversal_policy ENUM('CLOSE_ONLY','CLOSE_REVERSE') NOT NULL DEFAULT 'CLOSE_REVERSE',
  stop_loss_pct DECIMAL(8,5) NOT NULL DEFAULT 0.35,
  take_profit_pct DECIMAL(8,5) NOT NULL DEFAULT 0.70,
  max_position_minutes INT UNSIGNED NOT NULL DEFAULT 60,
  stress_multiplier DECIMAL(6,3) NOT NULL DEFAULT 2.5,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paper_trading_v2_accounts (
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL PRIMARY KEY,
  initial_balance DECIMAL(18,8) NOT NULL DEFAULT 100,
  cash_balance DECIMAL(18,8) NOT NULL DEFAULT 100,
  position_side ENUM('FLAT','LONG','SHORT') NOT NULL DEFAULT 'FLAT',
  quantity_btc DECIMAL(24,12) NOT NULL DEFAULT 0,
  entry_price DECIMAL(24,8) NULL,
  entry_market_data_id BIGINT UNSIGNED NULL,
  entry_prediction_id BIGINT UNSIGNED NULL,
  entry_at DATETIME NULL,
  entry_reason TEXT NULL,
  entry_fee_usd DECIMAL(18,8) NOT NULL DEFAULT 0,
  entry_slippage_usd DECIMAL(18,8) NOT NULL DEFAULT 0,
  reserved_cash DECIMAL(18,8) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
  total_fees DECIMAL(18,8) NOT NULL DEFAULT 0,
  total_slippage DECIMAL(18,8) NOT NULL DEFAULT 0,
  peak_equity DECIMAL(18,8) NOT NULL DEFAULT 100,
  max_drawdown_pct DECIMAL(10,6) NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paper_trading_decisions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL,
  prediction_id BIGINT UNSIGNED NOT NULL,
  prediction_created_at DATETIME NOT NULL,
  horizon VARCHAR(16) NOT NULL,
  predicted_direction ENUM('UP','DOWN','INDETERMINATE') NOT NULL,
  probability_up DECIMAL(8,5) NOT NULL,
  probability_down DECIMAL(8,5) NOT NULL,
  edge DECIMAL(8,5) NOT NULL,
  confidence DECIMAL(8,5) NOT NULL,
  regime VARCHAR(32) NOT NULL,
  regime_confidence DECIMAL(8,5) NULL,
  ensemble_signal DECIMAL(8,5) NOT NULL,
  strategy_score DECIMAL(12,8) NULL,
  expected_edge_pct DECIMAL(12,8) NULL,
  estimated_cost_pct DECIMAL(12,8) NOT NULL DEFAULT 0,
  position_before ENUM('FLAT','LONG','SHORT') NOT NULL,
  position_after ENUM('FLAT','LONG','SHORT') NOT NULL,
  decision VARCHAR(24) NOT NULL,
  reason_codes JSON NOT NULL,
  reason TEXT NOT NULL,
  signals_json JSON NULL,
  weights_json JSON NULL,
  market_data_id BIGINT UNSIGNED NULL,
  price_timestamp DATETIME NULL,
  available_at DATETIME NULL,
  ingested_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_paper_mode_prediction (mode, prediction_id),
  KEY idx_paper_decision_created (mode, created_at),
  CONSTRAINT fk_paper_decision_prediction FOREIGN KEY (prediction_id) REFERENCES predictions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paper_trading_v2_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL,
  decision_id BIGINT UNSIGNED NOT NULL,
  prediction_id BIGINT UNSIGNED NOT NULL,
  prediction_created_at DATETIME NOT NULL,
  horizon VARCHAR(16) NOT NULL,
  predicted_direction ENUM('UP','DOWN','INDETERMINATE') NOT NULL,
  probability_up DECIMAL(8,5) NOT NULL,
  probability_down DECIMAL(8,5) NOT NULL,
  edge DECIMAL(8,5) NOT NULL,
  confidence DECIMAL(8,5) NOT NULL,
  regime VARCHAR(32) NOT NULL,
  regime_confidence DECIMAL(8,5) NULL,
  ensemble_signal DECIMAL(8,5) NOT NULL,
  strategy_score DECIMAL(12,8) NULL,
  position_before ENUM('FLAT','LONG','SHORT') NOT NULL,
  position_after ENUM('FLAT','LONG','SHORT') NOT NULL,
  event_type ENUM('OPEN_LONG','CLOSE_LONG','OPEN_SHORT','CLOSE_SHORT') NOT NULL,
  market_data_id BIGINT UNSIGNED NOT NULL,
  price_timestamp DATETIME NOT NULL,
  available_at DATETIME NULL,
  ingested_at DATETIME NOT NULL,
  reference_price DECIMAL(24,8) NOT NULL,
  fill_price DECIMAL(24,8) NOT NULL,
  entry_price DECIMAL(24,8) NULL,
  exit_price DECIMAL(24,8) NULL,
  quantity_btc DECIMAL(24,12) NOT NULL,
  notional_usd DECIMAL(18,8) NOT NULL,
  fee_usd DECIMAL(18,8) NOT NULL DEFAULT 0,
  slippage_usd DECIMAL(18,8) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
  unrealized_pnl DECIMAL(18,8) NOT NULL DEFAULT 0,
  cash_after DECIMAL(18,8) NOT NULL,
  reason TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_paper_order_mode_time (mode, created_at),
  KEY idx_paper_order_prediction (prediction_id),
  CONSTRAINT fk_paper_order_decision FOREIGN KEY (decision_id) REFERENCES paper_trading_decisions(id) ON DELETE CASCADE,
  CONSTRAINT fk_paper_order_v2_prediction FOREIGN KEY (prediction_id) REFERENCES predictions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paper_trading_v2_trades (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL,
  side ENUM('LONG','SHORT') NOT NULL,
  entry_prediction_id BIGINT UNSIGNED NOT NULL,
  exit_prediction_id BIGINT UNSIGNED NOT NULL,
  entry_market_data_id BIGINT UNSIGNED NOT NULL,
  exit_market_data_id BIGINT UNSIGNED NOT NULL,
  entry_at DATETIME NOT NULL,
  exit_at DATETIME NOT NULL,
  entry_price DECIMAL(24,8) NOT NULL,
  exit_price DECIMAL(24,8) NOT NULL,
  quantity_btc DECIMAL(24,12) NOT NULL,
  gross_pnl DECIMAL(18,8) NOT NULL,
  fees_usd DECIMAL(18,8) NOT NULL,
  slippage_usd DECIMAL(18,8) NOT NULL,
  net_pnl DECIMAL(18,8) NOT NULL,
  entry_reason TEXT NOT NULL,
  exit_reason TEXT NOT NULL,
  hold_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_paper_trade_mode_time (mode, exit_at),
  CONSTRAINT fk_paper_trade_entry_prediction FOREIGN KEY (entry_prediction_id) REFERENCES predictions(id),
  CONSTRAINT fk_paper_trade_exit_prediction FOREIGN KEY (exit_prediction_id) REFERENCES predictions(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paper_trading_equity (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL,
  prediction_id BIGINT UNSIGNED NULL,
  market_data_id BIGINT UNSIGNED NOT NULL,
  price_timestamp DATETIME NOT NULL,
  available_at DATETIME NULL,
  ingested_at DATETIME NOT NULL,
  reference_price DECIMAL(24,8) NOT NULL,
  cash_balance DECIMAL(18,8) NOT NULL,
  position_side ENUM('FLAT','LONG','SHORT') NOT NULL,
  quantity_btc DECIMAL(24,12) NOT NULL,
  equity DECIMAL(18,8) NOT NULL,
  realized_pnl DECIMAL(18,8) NOT NULL,
  unrealized_pnl DECIMAL(18,8) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_paper_equity_mode_time (mode, created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS paper_trading_heartbeat (
  mode ENUM('DIRECTIONAL','STRATEGY') NOT NULL PRIMARY KEY,
  status ENUM('ACTIVE','STOPPED','ERROR') NOT NULL DEFAULT 'STOPPED',
  last_started_at DATETIME NULL,
  last_finished_at DATETIME NULL,
  last_prediction_id BIGINT UNSIGNED NULL,
  last_decision VARCHAR(24) NULL,
  last_reason TEXT NULL,
  last_error TEXT NULL,
  next_evaluation_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT IGNORE INTO paper_trading_config (mode) VALUES ('DIRECTIONAL'), ('STRATEGY');
INSERT IGNORE INTO paper_trading_v2_accounts (mode) VALUES ('DIRECTIONAL'), ('STRATEGY');
INSERT IGNORE INTO paper_trading_heartbeat (mode) VALUES ('DIRECTIONAL'), ('STRATEGY');
