CREATE TABLE IF NOT EXISTS athena50_shadow_predictions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  prediction_id BIGINT UNSIGNED NOT NULL,
  symbol VARCHAR(24) NOT NULL,
  horizon VARCHAR(16) NOT NULL,
  regime VARCHAR(32) NOT NULL,
  prediction_created_at DATETIME NOT NULL,
  model_status ENUM('READY','READY_PARTIAL','INSUFFICIENT_DATA','ERROR') NOT NULL,
  classic_signal DECIMAL(8,5) NULL,
  classic_confidence DECIMAL(8,5) NULL,
  shadow_signal DECIMAL(8,5) NULL,
  shadow_confidence DECIMAL(8,5) NULL,
  shadow_probability_up DECIMAL(8,5) NULL,
  feature_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  feature_total SMALLINT UNSIGNED NOT NULL DEFAULT 50,
  feature_vector JSON NOT NULL,
  group_summary JSON NOT NULL,
  group_ablation_predictions JSON NULL,
  group_ablation_results JSON NULL,
  candidate_predictions JSON NULL,
  candidate_results JSON NULL,
  market_data_id BIGINT UNSIGNED NULL,
  candle_timestamp DATETIME NULL,
  actual_direction ENUM('UP','DOWN','FLAT') NULL,
  classic_hit TINYINT(1) NULL,
  shadow_hit TINYINT(1) NULL,
  classic_brier DECIMAL(12,8) NULL,
  shadow_brier DECIMAL(12,8) NULL,
  evaluated_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_athena50_prediction (prediction_id),
  KEY idx_athena50_horizon_time (horizon,prediction_created_at),
  CONSTRAINT fk_athena50_prediction FOREIGN KEY (prediction_id) REFERENCES predictions(id) ON DELETE CASCADE
) ENGINE=InnoDB;
