<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/bootstrap.php';

use Prometheus\admin\AdminGuard;
use Prometheus\core\Database;

AdminGuard::requireAdmin();
if (session_status() === PHP_SESSION_NONE) session_start();
$symbol=prometheus_config('default_symbol','BTCUSDT');
$mode=($_GET['mode']??'DIRECTIONAL')==='STRATEGY'?'STRATEGY':'DIRECTIONAL';
$csrf=(string)($_SESSION['paper_trading_csrf']??'');
if($csrf===''){ $csrf=bin2hex(random_bytes(32)); $_SESSION['paper_trading_csrf']=$csrf; }
$notice=null;$error=null;$config=null;$account=null;$heartbeat=null;$priceRow=null;$predictions=[];$decisions=[];$trades=[];$curve=[];$moduleSignals=[];$stats=[];$athenaStats=[];$researchModes=[];$ready=true;

if(($_SERVER['REQUEST_METHOD']??'')==='POST'&&isset($_POST['save_config'])){
    if(!isset($_POST['csrf'])||!hash_equals($csrf,(string)$_POST['csrf']))$error='A sessão expirou. Atualize a página e tente novamente.';
    else {
        $allocation=(float)($_POST['allocation_pct']??0);$fee=(float)($_POST['fee_pct']??0);$slippage=(float)($_POST['slippage_pct']??0);
        $minEdge=(float)($_POST['min_edge_pct']??0);$minConfidence=(float)($_POST['min_confidence']??0);
        $cooldown=(int)($_POST['cooldown_minutes']??0);$stop=(float)($_POST['stop_loss_pct']??0);$take=(float)($_POST['take_profit_pct']??0);
        $maxMinutes=(int)($_POST['max_position_minutes']??0);$initial=(float)($_POST['initial_balance']??100);
        if($allocation<=0||$allocation>50||$fee<0||$fee>5||$slippage<0||$slippage>5||$minEdge<0||$minConfidence<0||$minConfidence>1||$cooldown<0||$stop<0||$take<0||$maxMinutes<1||$initial<1)$error='Revise os limites: alocação 0–50%, custos até 5%, confiança 0–1 e saldo inicial positivo.';
        else {
            try{
                $existing=Database::fetch('SELECT position_side FROM paper_trading_v2_accounts WHERE mode=?',[$mode]);
                if($existing&&$existing['position_side']!=='FLAT'&&isset($_POST['initial_balance']))$error='O saldo inicial só pode ser alterado com a posição zerada.';
                else{
                    Database::execute('UPDATE paper_trading_config SET enabled=?,initial_balance=?,allocation_pct=?,allow_short=?,fee_pct=?,slippage_pct=?,min_edge_pct=?,min_confidence=?,cooldown_minutes=?,reversal_policy=?,stop_loss_pct=?,take_profit_pct=?,max_position_minutes=? WHERE mode=?',[
                        isset($_POST['enabled'])?1:0,$initial,$allocation,isset($_POST['allow_short'])?1:0,$fee,$slippage,$minEdge,$minConfidence,$cooldown,
                        ($_POST['reversal_policy']??'CLOSE_REVERSE')==='CLOSE_ONLY'?'CLOSE_ONLY':'CLOSE_REVERSE',$stop,$take,$maxMinutes,$mode]);
                    $tradesExist=(int)(Database::fetch('SELECT COUNT(*) n FROM paper_trading_v2_trades WHERE mode=?',[$mode])['n']??0);
                    if(!$existing||($existing['position_side']==='FLAT'&&$tradesExist===0))Database::execute('UPDATE paper_trading_v2_accounts SET initial_balance=?,cash_balance=?,peak_equity=? WHERE mode=? AND position_side="FLAT"',[$initial,$initial,$initial,$mode]);
                    $notice='Configurações salvas para o modo '.$mode.'.';
                }
            }catch(Throwable $e){$error='Não foi possível salvar. Confirme se a migration 011 foi aplicada.';}
        }
    }
    $_SESSION['paper_trading_csrf']=bin2hex(random_bytes(32));$csrf=$_SESSION['paper_trading_csrf'];
}

try{
    $config=Database::fetch('SELECT * FROM paper_trading_config WHERE mode=?',[$mode]);
    $account=Database::fetch('SELECT * FROM paper_trading_v2_accounts WHERE mode=?',[$mode]);
    $heartbeat=Database::fetch('SELECT * FROM paper_trading_heartbeat WHERE mode=?',[$mode]);
    $priceRow=Database::fetch('SELECT id,close_price,open_time,close_time,available_at,ingested_at FROM market_data WHERE symbol=? AND interval_name=? AND close_time<=NOW() AND ingested_at IS NOT NULL AND ingested_at<=UTC_TIMESTAMP() AND temporal_quality IN ("EXACT","INGESTION_ONLY") AND (available_at IS NULL OR (available_at<=UTC_TIMESTAMP() AND ingested_at>=available_at)) ORDER BY close_time DESC LIMIT 1',[$symbol,prometheus_config('collector.market_interval','1m')]);
    if(!$config||!$account||!$heartbeat){$ready=false;} else {
        $decisions=Database::fetchAll('SELECT * FROM paper_trading_decisions WHERE mode=? ORDER BY id DESC LIMIT 40',[$mode]);
        $trades=Database::fetchAll('SELECT * FROM paper_trading_v2_trades WHERE mode=? ORDER BY exit_at DESC,id DESC LIMIT 30',[$mode]);
        $curve=Database::fetchAll('SELECT id,prediction_id,price_timestamp,reference_price,equity FROM paper_trading_equity WHERE mode=? ORDER BY created_at DESC,id DESC LIMIT 720',[$mode]);$curve=array_reverse($curve);
        foreach(['15m','1h','4h','24h'] as $h){$r=Database::fetch('SELECT * FROM predictions WHERE symbol=? AND horizon=? AND created_at<=NOW() ORDER BY id DESC LIMIT 1',[$symbol,$h]);if($r)$predictions[$h]=$r;}
        $latest15=$predictions['15m']??null;
        if($latest15){
            $signalData=json_decode((string)$latest15['signals_json'],true)?:[];$weights=json_decode((string)$latest15['weights_json'],true)?:[];
            $present=[];$denominator=0.0;
            foreach($signalData as $s){if(($s['status']??'AVAILABLE')==='AVAILABLE'||($s['status']??'')==='STALE'){$w=(float)($weights[$s['module']]??1);$eff=$w*max(.05,(float)$s['confidence']);$denominator+=$eff;$present[$s['module']]=['signal'=>(float)$s['value'],'confidence'=>(float)$s['confidence'],'weight'=>$w,'effective'=>$eff,'contribution'=>(float)$s['value']*$eff,'status'=>(string)($s['status']??'AVAILABLE')];}}
            foreach($present as &$s)$s['contribution_share']=$denominator>0?$s['effective']/$denominator*100:0;unset($s);$moduleSignals=$present;
        }
        $stats=Database::fetch('SELECT COUNT(*) n,SUM(net_pnl>0) wins,SUM(net_pnl<0) losses,SUM(GREATEST(net_pnl,0)) gains,SUM(ABS(LEAST(net_pnl,0))) loss_sum,SUM(fees_usd) fees,SUM(slippage_usd) slippage,AVG(net_pnl) expectancy FROM paper_trading_v2_trades WHERE mode=?',[$mode])??[];
        foreach(['DIRECTIONAL','STRATEGY'] as $researchMode){$researchAccount=Database::fetch('SELECT * FROM paper_trading_v2_accounts WHERE mode=?',[$researchMode]);$researchStats=Database::fetch('SELECT COUNT(*) n,SUM(net_pnl>0) wins,SUM(GREATEST(net_pnl,0)) gains,SUM(ABS(LEAST(net_pnl,0))) loss_sum,SUM(fees_usd+slippage_usd) costs FROM paper_trading_v2_trades WHERE mode=?',[$researchMode]);$researchModes[$researchMode]=['account'=>$researchAccount,'stats'=>$researchStats];}
        try{$athenaStats=Database::fetchAll('SELECT s.horizon,s.regime,COUNT(*) n,AVG(p.probability_up) classic_mean_p,AVG(s.shadow_probability_up) shadow_mean_p,AVG(s.classic_hit) classic_accuracy,AVG(s.shadow_hit) shadow_accuracy,AVG(s.classic_brier) classic_brier,AVG(s.shadow_brier) shadow_brier,AVG(CASE WHEN s.actual_direction="UP" THEN -LN(GREATEST(0.000000001,s.shadow_probability_up)) WHEN s.actual_direction="DOWN" THEN -LN(GREATEST(0.000000001,1-s.shadow_probability_up)) ELSE NULL END) shadow_logloss,AVG(CASE WHEN s.actual_direction="UP" THEN -LN(GREATEST(0.000000001,p.probability_up)) WHEN s.actual_direction="DOWN" THEN -LN(GREATEST(0.000000001,1-p.probability_up)) ELSE NULL END) classic_logloss FROM athena50_shadow_predictions s JOIN predictions p ON p.id=s.prediction_id WHERE s.model_status IN ("READY","READY_PARTIAL") AND s.actual_direction IN ("UP","DOWN") GROUP BY s.horizon,s.regime ORDER BY FIELD(s.horizon,"15m","1h","4h","24h"),s.regime');}catch(Throwable $ignored){$athenaStats=[];}
    }
}catch(Throwable $e){$ready=false;}

$price=(float)($priceRow['close_price']??0);$cash=(float)($account['cash_balance']??100);$qty=(float)($account['quantity_btc']??0);$side=(string)($account['position_side']??'FLAT');
$unrealized=$side==='FLAT'?0:($price-(float)$account['entry_price'])*$qty*($side==='LONG'?1:-1);
$equity=\Prometheus\core\PaperTrader::markedEquity($account??[],$price);
$initial=(float)($account['initial_balance']??100);$realized=(float)($account['realized_pnl']??0);$totalPnl=$equity-$initial;$returnPct=$initial>0?$totalPnl/$initial*100:0;
$nTrades=(int)($stats['n']??0);$wins=(int)($stats['wins']??0);$lossSum=(float)($stats['loss_sum']??0);$profitFactor=$lossSum>0?(float)($stats['gains']??0)/$lossSum:null;$winRate=$nTrades>0?$wins/$nTrades*100:null;
$heartbeatAge=$heartbeat&&$heartbeat['last_finished_at']?time()-strtotime((string)$heartbeat['last_finished_at']):PHP_INT_MAX;
$heartbeatStatus=!$ready?'MIGRATION PENDENTE':((int)($config['enabled']??0)===0?'PARADO':(($heartbeat['status']??'STOPPED')==='ERROR'?'ERRO':($heartbeatAge>300?'ATRASADO':'ATIVO')));
$decisionLabels=['OPEN_LONG'=>'ABRIR LONG','OPEN_SHORT'=>'ABRIR SHORT','CLOSE_LONG'=>'FECHAR LONG','CLOSE_SHORT'=>'FECHAR SHORT','HOLD_LONG'=>'MANTER LONG','HOLD_SHORT'=>'MANTER SHORT','NO_TRADE'=>'NÃO OPERAR','INDETERMINATE'=>'INDETERMINADA'];
$labels=['UP'=>'ALTA','DOWN'=>'BAIXA','INDETERMINATE'=>'INDEFINIDA'];
$series=[];$buyHold=[];$startPrice=(float)($curve[0]['reference_price']??0);
foreach($curve as $point){$series[]=['x'=>strtotime((string)$point['price_timestamp'])*1000,'y'=>(float)$point['equity']];$buyHold[]=['x'=>strtotime((string)$point['price_timestamp'])*1000,'y'=>$startPrice>0?$initial*(float)$point['reference_price']/$startPrice:$initial];}
function ptMoney(float $n):string{return '$'.number_format($n,2,',','.');}
function ptPct(float $n):string{return ($n>0?'+':'').number_format($n,2,',','.').'%';}
?>
<!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Paper trading - PROMETHEUS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="../assets/css/prometheus.css" rel="stylesheet"><style>.status-dot{display:inline-block;width:.6rem;height:.6rem;border-radius:50%;background:#8993a4;margin-right:.35rem}.status-active{background:#0f9f6e}.status-error,.status-late{background:#d64545}.sim-table td,.sim-table th{white-space:nowrap}.decision-open{color:#0f9f6e}.decision-close{color:#d64545}.signal-up{color:#0f9f6e}.signal-down{color:#d64545}</style></head><body>
<nav class="navbar navbar-expand-lg border-bottom"><div class="container-fluid px-4"><a class="navbar-brand fw-bold" href="../index.php">PROMETHEUS</a><div class="navbar-nav"><a class="nav-link" href="dashboard.php">Previsões</a><a class="nav-link active" href="simulation.php">Paper trading</a><a class="nav-link" href="modules.php">Módulos</a><a class="nav-link" href="performance.php">Desempenho</a><a class="nav-link" href="settings.php">Configurações</a></div><span class="navbar-text ms-auto">BTC/USDT · <?=htmlspecialchars($priceRow['close_time']??'sem cotação',ENT_QUOTES,'UTF-8')?></span></div></nav>
<main class="container-fluid p-4"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h1 class="h3 mb-1">Paper trading</h1><p class="text-muted mb-0">Simulação sem corretora, margem ou dinheiro real. DIRECTIONAL é diagnóstico; STRATEGY exige confirmação e expectativa líquida estimada.</p></div><span class="badge <?= $heartbeatStatus==='ATIVO'?'bg-success':($heartbeatStatus==='ERRO'||$heartbeatStatus==='ATRASADO'?'bg-danger':'bg-secondary') ?>">Simulador: <?=htmlspecialchars($heartbeatStatus)?></span></div>
<?php if($notice):?><div class="alert alert-success"><?=htmlspecialchars($notice)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<?php if(!$ready):?><div class="alert alert-warning">Aplique primeiro <code>sql/migrations/011_paper_trading_v2.sql</code>. A tela não grava operações sem as tabelas V2.</div><?php endif;?>
<ul class="nav nav-tabs mb-3"><li class="nav-item"><a class="nav-link <?=$mode==='DIRECTIONAL'?'active':''?>" href="?mode=DIRECTIONAL">DIRECTIONAL · diagnóstico</a></li><li class="nav-item"><a class="nav-link <?=$mode==='STRATEGY'?'active':''?>" href="?mode=STRATEGY">STRATEGY · rentabilidade</a></li></ul>
<section class="row g-3 mb-3">
<?php $cards=[['Capital inicial',ptMoney($initial)],['Equity atual',ptMoney($equity)],['Cash',ptMoney($cash)],['Exposição',ptMoney($qty*$price)],['Posição simulada',$side==='FLAT'?'FLAT':($side==='SHORT'?'SHORT simulado':'LONG')],['Entrada média',$side==='FLAT'?'—':ptMoney((float)$account['entry_price'])],['PnL aberto',ptMoney($unrealized)],['PnL realizado',ptMoney($realized)],['PnL total / retorno',ptMoney($totalPnl).' · '.ptPct($returnPct)],['Max drawdown',ptPct((float)($account['max_drawdown_pct']??0))],['Trades · acerto',$nTrades.' · '.($winRate===null?'—':number_format($winRate,1,',','.').'%')],['Profit factor',$profitFactor===null?'—':number_format($profitFactor,2,',','.').' · custos '.ptMoney((float)($account['total_fees']??0)+(float)($account['total_slippage']??0))]];foreach($cards as $c):?><div class="col-6 col-md-4 col-xl-2"><div class="metric h-100"><span><?=htmlspecialchars($c[0])?></span><strong class="fs-5"><?=htmlspecialchars($c[1])?></strong></div></div><?php endforeach;?>
</section>
<section class="row g-3 mb-3"><div class="col-12 col-xl-7"><div class="panel h-100"><h2>Decisão do PROMETHEUS</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Período</th><th>Direção</th><th>P(alta)</th><th>P(baixa)</th><th>Edge</th><th>Confiança</th></tr></thead><tbody><?php foreach(['15m','1h','4h','24h'] as $h):$p=$predictions[$h]??null;?><tr><td><?=$h?></td><?php if($p):?><td class="<?=$p['predicted_direction']==='UP'?'signal-up':($p['predicted_direction']==='DOWN'?'signal-down':'')?>"><?=$labels[$p['predicted_direction']]??$p['predicted_direction']?></td><td><?=number_format((float)$p['probability_up']*100,1,',','.')?>%</td><td><?=number_format((float)$p['probability_down']*100,1,',','.')?>%</td><td><?=number_format((float)$p['edge']*100,2,',','.')?> p.p.</td><td><?=number_format((float)$p['confidence']*100,1,',','.')?>%</td><?php else:?><td colspan="5" class="text-muted">Aguardando previsão</td><?php endif;?></tr><?php endforeach;?></tbody></table></div><p class="mb-0">Condição de mercado: <strong><?=htmlspecialchars((string)($predictions['15m']['regime']??'indisponível'))?></strong></p></div></div>
<div class="col-12 col-xl-5"><div class="panel h-100"><h2>Decisão do trader · <?=htmlspecialchars($mode)?></h2><?php $lastD=$decisions[0]??null;?><div class="display-6 mb-2"><?=htmlspecialchars($decisionLabels[$lastD['decision']??'']??'AGUARDANDO')?></div><p><?=htmlspecialchars((string)($lastD['reason']??'O cron ainda não registrou uma decisão para este modo.'))?></p><div class="small text-muted">Última execução: <?=htmlspecialchars((string)($heartbeat['last_finished_at']??'nunca'))?><br>Última previsão processada: <?=!empty($heartbeat['last_prediction_id'])?'#'.(int)$heartbeat['last_prediction_id']:'nenhuma'?><br>Próxima avaliação: <?=htmlspecialchars((string)($heartbeat['next_evaluation_at']??'aguardando cron'))?><br>Último erro: <?=htmlspecialchars((string)($heartbeat['last_error']??'nenhum'))?></div></div></div></section>
<section class="row g-3 mb-3"><div class="col-12 col-xl-7"><div class="panel"><h2>Diagnóstico do ensemble usado na previsão de 15m</h2><?php if(!$moduleSignals):?><p class="text-muted">Sem snapshot disponível.</p><?php else:?><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Módulo</th><th>Sinal</th><th>Conf.</th><th>Peso</th><th>Peso efetivo</th><th>Contribuição</th><th>Status</th></tr></thead><tbody><?php foreach($moduleSignals as $name=>$s):?><tr><td><?=htmlspecialchars($name)?></td><td><?=number_format($s['signal'],3,',','.')?></td><td><?=number_format($s['confidence']*100,1,',','.')?>%</td><td><?=number_format($s['weight'],3,',','.')?></td><td><?=number_format($s['effective'],3,',','.')?></td><td><?=number_format($s['contribution'],4,',','.')?> · <?=number_format($s['contribution_share'],1,',','.')?>%</td><td><?=htmlspecialchars($s['status'])?></td></tr><?php endforeach;?></tbody></table></div><small class="text-muted">Sinal bruto do ensemble: <?=number_format((float)($predictions['15m']['ensemble_signal']??0),4,',','.')?> · probabilidade calculada separadamente da decisão de trading.</small><?php endif;?></div></div>
<div class="col-12 col-xl-5"><div class="panel"><h2>Curva de equity × manter BTC</h2><canvas id="equityChart" height="220"></canvas><small class="text-muted">A curva começa no primeiro snapshot disponível. Buy &amp; Hold usa o mesmo preço inicial e capital inicial.</small></div></div></section>
<section class="panel mb-3"><h2>Pesquisa de estratégia</h2>
<p class="text-muted">A curva acima compara os modos paper com comprar e manter BTC. O valor incremental ATHENA-50 só pode ser medido nas previsões prospectivas avaliadas.</p>
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>Modelo / modo</th><th>Período</th><th>Amostras</th><th>Retorno líquido / acerto</th><th>Max drawdown / Brier</th><th>Profit factor / LogLoss</th><th>Custos</th></tr></thead><tbody>
<?php foreach($researchModes as $researchMode=>$rm):$ra=$rm['account']??[];$rs=$rm['stats']??[];$rn=(int)($rs['n']??0);$rwr=$rn>0?(float)($rs['wins']??0)/$rn*100:null;$rloss=(float)($rs['loss_sum']??0);$rpf=$rloss>0?(float)($rs['gains']??0)/$rloss:null;$rside=(string)($ra['position_side']??'FLAT');$rqty=(float)($ra['quantity_btc']??0);$rentry=(float)($ra['entry_price']??0);$rreserve=(float)($ra['reserved_cash']??0);$re=(float)($ra['cash_balance']??0)+($rside==='LONG'?$rqty*$price:($rside==='SHORT'?$rreserve+($price-$rentry)*$rqty*-1:$rreserve));?>
<tr><td>PROMETHEUS · <?=htmlspecialchars($researchMode)?></td><td>desde o início</td><td><?=$rn?></td><td><?=ptMoney($re-(float)($ra['initial_balance']??100))?> · <?=$rwr===null?'—':number_format($rwr,1,',','.').'%'?></td><td><?=ptPct((float)($ra['max_drawdown_pct']??0))?></td><td><?=$rpf===null?'—':number_format($rpf,2,',','.')?></td><td><?=ptMoney((float)($rs['costs']??0))?></td></tr><?php endforeach;?>
<?php foreach($athenaStats as $s):?><tr><td>ATHENA_CLASSIC × ATHENA-50 shadow</td><td><?=htmlspecialchars((string)$s['horizon'].' · '.$s['regime'])?></td><td><?=(int)$s['n']?></td><td><?=number_format((float)$s['classic_accuracy']*100,1,',','.')?>% × <?=number_format((float)$s['shadow_accuracy']*100,1,',','.')?>%</td><td><?=number_format((float)$s['classic_brier'],4,',','.')?> × <?=number_format((float)$s['shadow_brier'],4,',','.')?></td><td><?=number_format((float)$s['classic_logloss'],4,',','.')?> × <?=number_format((float)$s['shadow_logloss'],4,',','.')?></td><td>—</td></tr><?php endforeach;?>
<?php if(!$athenaStats):?><tr><td>ATHENA_CLASSIC × ATHENA-50 shadow</td><td>mesmas previsões avaliadas</td><td colspan="5" class="text-muted">Sem amostra avaliada ainda, ou migration 012 pendente.</td></tr><?php endif;?></tbody></table></div>
<small class="text-muted">A tabela não declara estratégia lucrativa. Leia as métricas junto do N; o shadow não participa do ensemble.</small></section>
<section class="panel mb-3"><h2>Configurações persistentes · <?=htmlspecialchars($mode)?></h2><form method="post" class="row g-2 align-items-end"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="save_config" value="1"><div class="col-auto form-check ms-2"><input class="form-check-input" type="checkbox" name="enabled" id="enabled" <?=!empty($config['enabled'])?'checked':''?>><label class="form-check-label" for="enabled">Ativo</label></div><div class="col-auto form-check ms-2"><input class="form-check-input" type="checkbox" name="allow_short" id="allowShort" <?=!empty($config['allow_short'])?'checked':''?>><label class="form-check-label" for="allowShort">Permitir SHORT sintético</label></div><?php $fields=[['initial_balance','Saldo inicial',100,.01],['allocation_pct','Alocação %',25,.1],['fee_pct','Taxa % por lado',.1,.001],['slippage_pct','Slippage % por lado',.02,.001],['min_edge_pct','Margem mínima %',.03,.001],['min_confidence','Confiança mínima (0–1)',.2,.01],['cooldown_minutes','Intervalo (min)',15,1],['stop_loss_pct','Stop %',.35,.01],['take_profit_pct','Alvo %',.7,.01],['max_position_minutes','Tempo máximo (min)',60,1]];foreach($fields as [$key,$label,$fallback,$step]):?><div class="col-6 col-md-3 col-xl-2"><label class="form-label small" for="<?=htmlspecialchars($key)?>"><?=htmlspecialchars($label)?></label><input class="form-control form-control-sm" id="<?=htmlspecialchars($key)?>" name="<?=htmlspecialchars($key)?>" type="number" step="<?=$step?>" value="<?=htmlspecialchars((string)($config[$key]??$fallback))?>"></div><?php endforeach;?><div class="col-6 col-md-3 col-xl-2"><label class="form-label small" for="reversal_policy">Reversão</label><select class="form-select form-select-sm" name="reversal_policy" id="reversal_policy"><option value="CLOSE_REVERSE" <?=($config['reversal_policy']??'')==='CLOSE_REVERSE'?'selected':''?>>Fecha e inverte</option><option value="CLOSE_ONLY" <?=($config['reversal_policy']??'')==='CLOSE_ONLY'?'selected':''?>>Só fecha</option></select></div><div class="col-auto"><button class="btn btn-primary btn-sm" type="submit">Salvar configuração</button></div></form><small class="text-muted d-block mt-2">Cada modo usa uma conta paper independente. DIRECTIONAL acompanha a direção; STRATEGY pode registrar NÃO OPERAR. Alocação máxima permitida: 50%, sem alavancagem.</small></section>
<section class="panel mb-3"><h2>Registro de decisões · inclusive sem operação</h2><div class="table-responsive"><table class="table table-sm sim-table align-middle"><thead><tr><th>Data e hora</th><th>ID previsão</th><th>Horizonte</th><th>Direção</th><th>P alta</th><th>P baixa</th><th>Edge</th><th>Conf.</th><th>Regime</th><th>Decisão</th><th>Motivo</th></tr></thead><tbody><?php foreach($decisions as $d):?><tr><td><?=htmlspecialchars((string)$d['created_at'])?></td><td>#<?=(int)$d['prediction_id']?></td><td><?=htmlspecialchars((string)$d['horizon'])?></td><td><?=htmlspecialchars($labels[$d['predicted_direction']]??$d['predicted_direction'])?></td><td><?=number_format((float)$d['probability_up']*100,1,',','.')?>%</td><td><?=number_format((float)$d['probability_down']*100,1,',','.')?>%</td><td><?=number_format((float)$d['edge']*100,2,',','.')?></td><td><?=number_format((float)$d['confidence']*100,1,',','.')?>%</td><td><?=htmlspecialchars((string)$d['regime'])?></td><td><?=htmlspecialchars($decisionLabels[$d['decision']]??$d['decision'])?></td><td title="<?=htmlspecialchars((string)$d['reason'],ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars(mb_strimwidth((string)$d['reason'],0,70,'…','UTF-8'))?></td></tr><?php endforeach;?><?php if(!$decisions):?><tr><td colspan="11" class="text-muted">Ainda não há previsões processadas pelo modo <?=htmlspecialchars($mode)?>. O heartbeat acima indica se o cron está chegando ao simulador.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel"><h2>Operações encerradas</h2><div class="table-responsive"><table class="table table-sm sim-table"><thead><tr><th>Entrada</th><th>Saída</th><th>Posição</th><th>Preço entrada</th><th>Preço saída</th><th>Quantidade</th><th>Duração</th><th>PnL bruto</th><th>Taxas</th><th>Slippage</th><th>PnL líquido</th><th>Motivo entrada / saída</th></tr></thead><tbody><?php foreach($trades as $t):?><tr><td><?=htmlspecialchars((string)$t['entry_at'])?></td><td><?=htmlspecialchars((string)$t['exit_at'])?></td><td><?=$t['side']==='SHORT'?'SHORT simulado':'LONG'?></td><td><?=ptMoney((float)$t['entry_price'])?></td><td><?=ptMoney((float)$t['exit_price'])?></td><td><?=number_format((float)$t['quantity_btc'],8,',','.')?> BTC</td><td><?=floor((int)$t['hold_seconds']/60)?> min</td><td><?=ptMoney((float)$t['gross_pnl'])?></td><td><?=ptMoney((float)$t['fees_usd'])?></td><td><?=ptMoney((float)$t['slippage_usd'])?></td><td><?=ptMoney((float)$t['net_pnl'])?></td><td title="<?=htmlspecialchars((string)$t['entry_reason'].' / '.(string)$t['exit_reason'],ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars(mb_strimwidth((string)$t['entry_reason'].' / '.(string)$t['exit_reason'],0,55,'…','UTF-8'))?></td></tr><?php endforeach;?><?php if(!$trades):?><tr><td colspan="12" class="text-muted">Nenhuma posição encerrada neste modo.</td></tr><?php endif;?></tbody></table></div></section>
</main><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>
const equitySeries=<?=json_encode($series,JSON_UNESCAPED_UNICODE)?>,holdSeries=<?=json_encode($buyHold,JSON_UNESCAPED_UNICODE)?>;
const chart=document.getElementById('equityChart');if(chart&&equitySeries.length){new Chart(chart,{type:'line',data:{datasets:[{label:'PROMETHEUS <?=htmlspecialchars($mode,ENT_QUOTES,'UTF-8')?>',data:equitySeries,borderColor:'#0f9f6e',backgroundColor:'rgba(15,159,110,.1)',pointRadius:0,tension:.15},{label:'Comprar e manter BTC',data:holdSeries,borderColor:'#5276c7',pointRadius:0,tension:.15}]},options:{responsive:true,parsing:false,scales:{x:{type:'linear',ticks:{callback:v=>new Date(v).toLocaleString('pt-BR')}},y:{ticks:{callback:v=>'$'+Number(v).toFixed(2)}}}}});}
</script></body></html>
